services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "123456" ]
    network_mode: "host"

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authorization
    network_mode: "host"